frontend: Recognise "Starting up..." health state
During a recent restart of the codesearch server, I noticed that
the Hound UI displays a (plaintext) message pointing at /_health, but
the Beta UI displayed instead:

> PHP Warning: foreach() argument must be of type array|object, null given
> in /codesearch/frontend/src/Codesearch.php on line 98

And:

> Internal error
>
> TypeError: Wikimedia\Codesearch\Codesearch::getCachedConfig():
> Return value must be of type array, null returned

Fix this by adding a check, and also by rendering a custom page
instead of the Internal error page. The custom page has two notable
improvements over Hound:

1. It includes the form UI as normal, allowing you to easily switch
   to a different index, under the assumption that usually the main
   one is the slowest to start up, but others are available sooner.
2. Make the health URL a clickable link.

Test Plan:
* Set `$val = null; # ..` to trigger this new condition.

Change-Id: Idb18c271837065595fb64a64acc5f689388e4d8e